WORKFLOW_SCRIPT = simulate_data_collection.py
PROSPECTIVE_LINEAGE_DATA = corrected_image
RETROSPECTIVE_LINEAGE_DATA = corrected_image_path
RETROSPECTIVE_LINEAGE_VALUE = 'run/data/DRT240/DRT240_12000eV_002.img'
include ../common.Makefile
