WORKFLOW_SCRIPT = iterative_emphasis.py
PROSPECTIVE_LINEAGE_DATA = emphasized_greeting
RETROSPECTIVE_LINEAGE_DATA = displayed_greeting
RETROSPECTIVE_LINEAGE_VALUE = 'Back again?!?!?!'
include ../common.Makefile
