WORKFLOW_SCRIPT = emphasis_function.py
PROSPECTIVE_LINEAGE_DATA = emphasized_greeting
RETROSPECTIVE_LINEAGE_DATA = emphasized_greeting
RETROSPECTIVE_LINEAGE_VALUE = 'Back again?!?!?!'
include ../common.Makefile
