WORKFLOW_SCRIPT = custom_hello_world.py
PROSPECTIVE_LINEAGE_DATA = custom_greeting
RETROSPECTIVE_LINEAGE_DATA = displayed_greeting
RETROSPECTIVE_LINEAGE_VALUE = 'Goodbye World!!'
include ../common.Makefile
