WORKFLOW_SCRIPT = greeting_from_file.py
PROSPECTIVE_LINEAGE_DATA = displayed_greeting
RETROSPECTIVE_LINEAGE_DATA = displayed_greeting
RETROSPECTIVE_LINEAGE_VALUE = 'Back again?!?!?!'
include ../common.Makefile
